export const UPDATE_GAME_STATE = 'UPDATE_GAME_STATE';
export const SET_STATUS_FINISHED = 'SET_STATUS_FINISHED';
export const SET_STATUS_COUNTDOWN = 'SET_STATUS_COUNTDOWN';
export const SET_STATUS_PLAYING = 'SET_STATUS_PLAYING';
export const SET_STATUS_POSTGAME = 'SET_STATUS_POSTGAME';
export const INCREMENT_GAME_TIME = 'INCREMENT_GAME_TIME';
export const INIT_GAME = 'INIT_GAME';
export const RESET_GAME = 'RESET_GAME';
