export const UPDATE_GAME_STATE = 'UPDATE_GAME_STATE';
export const SET_STATUS_FINISHED = 'SET_STATUS_FINISHED';
export const SET_STATUS_COUNTDOWN = 'SET_STATUS_COUNTDOWN';
export const SET_STATUS_PLAYING = 'SET_STATUS_PLAYING';
